In [1]:
!pip install numpy
import numpy as np

In [2]:
a=np.array([1,2,3,4,'a']) #single data type

In [3]:
a

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [37]:

b=np.array(10)
c=np.array([1,2,3])
d=np.array([[1,2],[2,4]])
e=np.array([[[1,2],[5,6],[7,8]]])
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


0
1
2
3


In [15]:
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

()
(3,)
(2, 2)
(1, 3, 2)


In [22]:
print(type(b))
type(c)
d.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [20]:
print(len(d))

2


In [23]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.full((4,4),6,dtype=str)

array([['6', '6', '6', '6'],
       ['6', '6', '6', '6'],
       ['6', '6', '6', '6'],
       ['6', '6', '6', '6']], dtype='<U1')

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
x=[1,2,3,4,5,6]
np.diag(x)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [42]:
#reshape , factors of numbers
x=np.arange(1,13)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [45]:
x1=x.reshape(3,4)
print(x1)
print(x1.shape)
print(x1.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [46]:
x2=x.reshape(2,3,2)
print(x2)
print(x2.shape)
print(x2.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [49]:
#convert to old dimension #ravel #like undo
p=x.ravel()
print(p)
print(p.shape)
print(p.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
